### ISSUE TITLE
GB Survey Status Changing for every GB Import

### ISSUE THREAD

**Issue by matthewandrewpalmer** [ONSdigital/lfs-imports#8]
On Import, accept and reject for a specific week, the status is being set for every GB file in the same Batch in the gb_batch_items table.

![image](https://user-images.githubusercontent.com/38406765/69980061-632ca700-1527-11ea-88fb-8369a1a4df6c.png)

Which looks really odd in the UI
![image](https://user-images.githubusercontent.com/38406765/69980026-4f814080-1527-11ea-8dbe-d64cd9afc2f7.png)

**Comment by pds2208** [comment]
Fixed in branch gb_batch_fix. PR is outstanding.
